export default {
  gameDiv: document.getElementById("game"),
  player1Info: document.getElementById("player1-info"),
  player1Gameboard: document.getElementById("player1-gameboard"),
  player2Info: document.getElementById("player2-info"),
  player2Gameboard: document.getElementById("player2-gameboard"),
  restartBtn: document.getElementById("restart-btn"),
  placementForm: document.getElementById("placement-form"),
  placementBoard: document.getElementById("placement-board"),
  placementInfo: document.getElementById("placement-info"),
  approveBtn: document.getElementById("placement-approve-btn"),
  rotateBtn: document.getElementById("rotate-placement-btn"),
  removeBtn: document.getElementById("remove-placement-btn"),
  shipDirInfo: document.getElementById("ship-direction"),
  shipLengthInfo: document.getElementById("ship-length"),
  modal: document.getElementById("gameover-modal"),
  winModal: document.getElementById("win-modal"),
  winnerModal: document.getElementById("winner"),
  restartModalBtn: document.getElementById("restart-modal-btn"),
  statsModal: document.getElementById("stats-modal"),
  infoBtn: document.querySelectorAll(".info-btn"),
  infoModal: document.getElementById("info-modal"),
  infoCloseBtn: document.getElementById("modal-close-btn"),
};
